#' Prepare Boxplots
#'
#' Takes in raw and pre-processed data, regression models and
#' a list of helpers to prepare a selected boxplot.
#'
#' @param d0 Raw data as generated by \code{import_data}
#' @param df Pre-processed data as generated by
#'    \code{preprocess_data}
#' @param fit A list of linear regressions generated by
#'    \code{fit_regressions}
#' @param help A helpers list generated by \code{extract_helpers}
#' @param scl Scaling data.frame generated by \code{preprocess_data}
#' @param rt_vars Response times variables names generated by
#'    \code{extract_rt_variables}
#' @param which A character indicating whether subcortical structures
#'    ("brains", default), neuropsychology measures stratified by OSA
#'    ("cognition_1") or neuropsychology measures stratified by PD
#'    ("cognition_2") should be plotted.
#'
#' @returns A list with regressions, one per outcome
#'
#' @export
boxplots <- function(d0, df, fit, help, scl, rt_vars, which = "brains") {
  # brain structures ----
  if (which == "brains") {
    # Prepare results for p-values reported in the boxplot:
    p <- fit |>
      mass() |>
      dplyr::mutate(
        p = paste0(zerolead(p.value), bh_adjust(p.value)), # p-value labels
        x = "Diagnosis",
        Diagnosis = dplyr::if_else(SUBJ == "PD", "PD", "CON"),
        group1 = dplyr::if_else(term == "PD - CON", "PD", Diagnosis),
        group2 = dplyr::if_else(term == "PD - CON", "CON", Diagnosis),
        side = unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$subco, side[name == y[i]])
        }),
        use.names = FALSE
        ),
        structure = factor(
          unlist(sapply(seq_len(dplyr::n()), function(i) {
            with(help$subco, structure[name == y[i]])
          }),
          use.names = FALSE
          ),
          levels = unique(help$subco$structure),
          ordered = TRUE
        )
      )
    # Add vertical displacements:
    p$y.position <- unlist(sapply(seq_len(nrow(p)), function(i) {
      ifelse(
        p$term[i] == "PD - CON",
        max(df[ , paste0("c", p$y[i])]) + 3 * sd(df[ , paste0("c", p$y[i])]),
        max(df[ , paste0("c", p$y[i])]) + .5 * sd(df[ , paste0("c", p$y[i])])
      )
    }))
    # Plot it:
    fig <- d0 |>
      dplyr::select(SUBJ, AHI.F, tidyselect::all_of(help$subco$scaled)) |>
      tidyr::pivot_longer(
        cols = tidyselect::all_of(help$subco$scaled),
        values_to = "volume",
        names_to = "struct"
      ) |>
      dplyr::mutate(
        side = unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$subco, side[scaled == struct[i]])
        }),
        use.names = FALSE
        ),
        structure = factor(
          unlist(sapply(seq_len(dplyr::n()), function(i) {
            with(help$subco, structure[scaled == struct[i]])
          }),
          use.names = FALSE
          ),
          levels = unique(help$subco$structure),
          ordered = TRUE
        ),
        Diagnosis = dplyr::if_else(SUBJ == "PD", "PD", "CON"),
        `OSA: ` = factor(
          dplyr::if_else(AHI.F == "H", "OSA+", "OSA-"),
          levels = c("OSA-","OSA+"),
          ordered = TRUE
        )
      ) |>
      # Plotting proper:
      ggplot2::ggplot() +
      ggplot2::aes(y = volume, x = Diagnosis) +
      ggplot2::geom_boxplot(
        ggplot2::aes(fill = `OSA: `),
        width = .6,
        position = ggplot2::position_dodge(.7),
        linewidth = .75
      ) +
      ggplot2::geom_dotplot(
        ggplot2::aes(fill = `OSA: `),
        binaxis = "y",
        stackdir = "center",
        position = ggplot2::position_dodge(.7),
        dotsize = 1.5
      ) +
      ggplot2::labs(y = bquote("Standardized volume "(mm^3))) +
      ggh4x::facet_grid2(structure ~ side, scales = "free_y", independent = "y") +
      ggplot2::scale_fill_manual(values = c("#64CDCC","#F9A729")) +
      ggpubr::stat_pvalue_manual( # p-values for simple main effects
        subset(p, term != "PD - CON"),
        label = "p",
        size = 3,
        position = ggplot2::position_dodge(.7),
        remove.bracket = TRUE
      ) +
      ggpubr::stat_pvalue_manual( # p-values for interactions
        subset(p, term == "PD - CON"),
        label = "p",
        size = 3,
        tip.length = .1,
        vjust = -.33
      ) +
      ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, .19))) +
      ggplot2::theme_bw(base_size = 10) +
      ggplot2::theme(legend.position = "bottom", panel.grid = ggplot2::element_blank())
    # Save it:
    #ggsave(
    #  plot = last_plot(),
    #  filename = here("figures","subcortical_boxplots.jpg"),
    #  dpi = 300,
    #  width = 6,
    #  height = 10.5
    #)
  } else if (which == "cognition_1") {
    # cognition: PD/OSA interaction ----
    p <- fit |>
      mass() |>
      dplyr::mutate(
        p = paste0(zerolead(p.value), bh_adjust(p.value)), # p-value labels
        x = "Diagnosis",
        Diagnosis = dplyr::if_else(SUBJ == "PD", "PD", "CON"),
        group1 = dplyr::if_else(term == "PD - CON", "PD", Diagnosis),
        group2 = dplyr::if_else(term == "PD - CON", "CON", Diagnosis),
        test = factor(
          unlist(sapply(seq_len(dplyr::n()), function(i) {
            with(help$psych, label[variable == y[i]])
          }),
          use.names = FALSE
          ),
          levels = help$psych$label,
          ordered = TRUE
        )
      )
    # Add vertical displacement:
    p$y.position = unlist(sapply(seq_len(nrow(p)), function(i) {
      dplyr::case_when(
        p$term[i] == "PD - CON" & !(p$y[i] %in% rt_vars) ~ max(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] + 2 * scl[p$y[i], "SD"],
        p$term[i] != "PD - CON" & !(p$y[i] %in% rt_vars) ~ max(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] + .3 * scl[p$y[i], "SD"],
        p$term[i] == "PD - CON" & p$y[i] %in% rt_vars ~ exp(-(min(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] - 1 * scl[p$y[i], "SD"])),
        p$term[i] != "PD - CON" & p$y[i] %in% rt_vars ~ exp(-(min(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] - .2 * scl[p$y[i], "SD"]))
      )
    }))
    # Plot it:
    fig <- d0 |>
      dplyr::select(SUBJ, AHI.F, tidyselect::all_of(help$psych$variable)) |>
      tidyr::pivot_longer(cols = tidyselect::all_of(help$psych$variable), values_to = "score", names_to = "test") |>
      dplyr::mutate(
        test = factor(
          unlist(sapply(seq_len(dplyr::n()), function(i) {
            with(help$psych, label[variable == test[i]])
          }),
          use.names = FALSE
          ),
          levels = help$psych$label,
          ordered = TRUE
        ),
        Diagnosis = dplyr::if_else(SUBJ == "PD", "PD", "CON"),
        `OSA: ` = factor(
          dplyr::if_else(AHI.F == "H", "OSA+", "OSA-"),
          levels = c("OSA-","OSA+"),
          ordered = TRUE
        )
      ) |>
      ggplot2::ggplot() +
      ggplot2::aes(y = score, x = Diagnosis) +
      ggplot2::geom_boxplot(ggplot2::aes(fill = `OSA: `), width = .6, position = ggplot2::position_dodge(.7), linewidth = .75) +
      ggplot2::geom_dotplot(
        ggplot2::aes(fill = `OSA: `),
        binaxis = "y",
        stackdir = "center",
        position = ggplot2::position_dodge(.7),
        dotsize = 1.5
      ) +
      ggplot2::labs(y = "Test score") +
      ggplot2::facet_wrap(~ test, scales = "free", nrow = 5) +
      ggplot2::scale_fill_manual(values = c("#64CDCC","#F9A729")) +
      ggpubr::stat_pvalue_manual( # p-values for simple main effects
        subset(p, term != "PD - CON"),
        label = "p",
        size = 3,
        position = ggplot2::position_dodge(.7),
        remove.bracket = TRUE
      ) +
      ggpubr::stat_pvalue_manual( # p-values for interactions
        subset(p, term == "PD - CON"),
        label = "p",
        size = 3,
        tip.length = .1,
        vjust = -.33
      ) +
      ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, .19))) +
      ggplot2::theme_bw(base_size = 11) +
      ggplot2::theme(legend.position = "bottom", panel.grid = ggplot2::element_blank())
    # Save it:
    #ggsave(
    #  plot = last_plot(),
    #  filename = here("figures","cognition_boxplots.jpg"),
    #  dpi = 300,
    #  width = 9,
    #  height = 9
    #)
  } else if (which == "cognition_2") {
    # cognition: PD main effects ----
    p <- fit |>
      mass(type = "full") |>
      dplyr::filter(term == "SUBJ") |>
      dplyr::mutate(
        p = paste0(zerolead(p.value), bh_adjust(p.value)), # p-value labels
        x = "OSA",
        OSA = dplyr::if_else(AHI.F == "H", "OSA+", "OSA-"),
        group1 = dplyr::if_else(is.na(OSA), "OSA-", OSA),
        group2 = dplyr::if_else(is.na(OSA), "OSA+", OSA),
        test = factor(
          unlist(sapply(seq_len(dplyr::n()), function(i) {
            with(help$psych, label[variable == y[i]])
          }),
          use.names = FALSE
          ),
          levels = help$psych$label,
          ordered = TRUE
        )
      )
    # Add vertical displacement:
    p$y.position = unlist(sapply(seq_len(nrow(p)), function(i) {
      dplyr::case_when(
        is.na(p$AHI.F[i]) & !(p$y[i] %in% rt_vars) ~ max(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] + 1 * scl[p$y[i], "SD"],
        !is.na(p$AHI.F[i]) & !(p$y[i] %in% rt_vars) ~ max(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] + .2 * scl[p$y[i], "SD"],
        is.na(p$AHI.F[i]) & p$y[i] %in% rt_vars ~ exp(-(min(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] - .5 * scl[p$y[i], "SD"])),
        !is.na(p$AHI.F[i]) & p$y[i] %in% rt_vars ~ exp(-(min(df[ , p$y[i]], na.rm = TRUE) * scl[p$y[i], "SD"] + scl[p$y[i], "M"] - .1 * scl[p$y[i], "SD"]))
      )
    }))
    # Plot it:
    fig <- d0 |>
      dplyr::select(SUBJ, AHI.F, tidyselect::all_of(help$psych$variable)) |>
      tidyr::pivot_longer(cols = tidyselect::all_of(help$psych$variable), values_to = "score", names_to = "test") |>
      dplyr::mutate(
        test = factor(
          unlist(sapply(seq_len(dplyr::n()), function(i) {
            with(help$psych, label[variable == test[i]])
          }),
          use.names = FALSE
          ),
          levels = help$psych$label,
          ordered = TRUE
        ),
        `Diagnosis: ` = dplyr::if_else(SUBJ == "PD", "PD", "CON"),
        OSA = factor(
          dplyr::if_else(AHI.F == "H", "OSA+", "OSA-"),
          levels = c("OSA-","OSA+"),
          ordered = TRUE
        )
      ) |>
      ggplot2::ggplot() +
      ggplot2::aes(y = score, x = OSA) +
      ggplot2::geom_boxplot(ggplot2::aes(fill = `Diagnosis: `), width = .6, position = ggplot2::position_dodge(.7), linewidth = .75) +
      ggplot2::geom_dotplot(
        ggplot2::aes(fill = `Diagnosis: `),
        binaxis = "y",
        stackdir = "center",
        position = ggplot2::position_dodge(.7),
        dotsize = 1.5
      ) +
      ggplot2::labs(y = "Test score", x = NULL) +
      ggplot2::facet_wrap(~ test, scales = "free", nrow = 5) +
      ggplot2::scale_fill_manual(values = c("deepskyblue","red2")) +
      ggpubr::stat_pvalue_manual( # p-values for simple main effects
        subset(p, !is.na(OSA)),
        label = "p",
        size = 3,
        position = ggplot2::position_dodge(.7),
        remove.bracket = TRUE
      ) +
      ggpubr::stat_pvalue_manual( # p-values for interactions
        subset(p, is.na(OSA)),
        label = "p",
        size = 3,
        tip.length = 0,
        vjust = -.2
      ) +
      ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, .19))) +
      ggplot2::theme_bw(base_size = 11) +
      ggplot2::theme(legend.position = "bottom", panel.grid = ggplot2::element_blank())
    # Save it:
    #ggsave(
    #  plot = last_plot(),
    #  filename = here("figures","cognition_boxplots_group_contrast.jpg"),
    #  dpi = 300,
    #  width = 9,
    #  height = 9
    #)
  }
  fig
}
