#' Correlate hippocampi volumes
#'
#' Correlates volume estimates of hippocampi estimated
#' by different approaches.
#'
#' @param d0 Tibble. Raw data as generated by \code{import_data}.
#' @param d1 Tibble. Preprocessed data as generated by
#'   \code{preprocess_data}.
#' @param help List. Helpers as generated by \code{extract_helpers}.
#'
#' @returns A list of ggplots.
#'
#' @export
correlate_volumes <- function(d0, d1, help) {
  # Extract variable of interest names:
  struct <- tibble::tibble(
    side = c(rep("Left", 6), rep("Right", 6)),
    source = rep(c("aseg.stat", "segmentHA", "synthseg"), 4),
    measure = rep(c(rep("raw", 3), rep("scaled", 3)), 2),
    data = c(rep("d0", 3), rep("d1", 2), rep("d0", 4), rep("d1", 2), "d0"),
    column = c(
      subset(help$subco, structure == "Hippocampus" & side == "Left")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Left")$var,
      "Left_Hippocampus_synthseg",
      subset(help$subco, structure == "Hippocampus" & side == "Left")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Left")$name,
      "Left_Hippocampus_synthseg_scaled",
      subset(help$subco, structure == "Hippocampus" & side == "Right")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Right")$var,
      "Right_Hippocampus_synthseg",
      subset(help$subco, structure == "Hippocampus" & side == "Right")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Right")$name,
      "Right_Hippocampus_synthseg_scaled"
    )
  )
  # Prepare data:
  df <- d0 |>
    dplyr::select(
      Study.ID, SUBJ, AHI.F,
      tidyselect::all_of(subset(struct, data == "d0")$column)
    ) |>
    dplyr::left_join(
      d1 |> dplyr::select(
        Study.ID, SUBJ, AHI.F,
        tidyselect::all_of(subset(struct, data == "d1")$column)
      ),
      by = dplyr::join_by(Study.ID, SUBJ, AHI.F),
      suffix = c("_raw", "_scaled")
    ) |>
    dplyr::mutate(
      PD = dplyr::if_else(SUBJ == "PD", TRUE, FALSE),
      OSA = dplyr::if_else(AHI.F == "H", TRUE, FALSE)
    ) |>
    dplyr::rename( # dirty by hand to save time
      "Raw_Left_aseg.stat" = "Left_Hippocampus_raw",
      "Raw_Left_segmentHA" = "Whole_hippocampus_lhx",
      "Raw_Left_synthseg" = "Left_Hippocampus_synthseg",
      "Scaled_Left_aseg.stat" = "Left_Hippocampus_scaled",
      "Scaled_Left_segmentHA" = "Hippocampus_left_AI",
      "Scaled_Left_synthseg" = "Left_Hippocampus_synthseg_scaled",
      "Raw_Right_aseg.stat" = "Right_Hippocampus_raw",
      "Raw_Right_segmentHA" = "Whole_hippocampus_rhx",
      "Raw_Right_synthseg" = "Right_Hippocampus_synthseg",
      "Scaled_Right_aseg.stat" = "Right_Hippocampus_scaled",
      "Scaled_Right_segmentHA" = "Hippocampus_right_AI",
      "Scaled_Right_synthseg" = "Right_Hippocampus_synthseg_scaled",
    ) |>
    tidyr::pivot_longer(
      cols = dplyr::matches("^(Raw|Scaled)_(Left|Right)"),
      names_to = c("scale", "side", "algo"),
      names_pattern = "^(Raw|Scaled)_(Left|Right)_(.*)$",
      values_to = "value"
    ) |>
    # Clean algorithm names
    dplyr::mutate(
      scale = factor(scale, levels = c("Raw", "Scaled")),
      side = factor(side, levels = c("Left", "Right")),
      algo = factor(algo, levels = c("aseg.stat", "segmentHA", "synthseg"))
    ) |>
    tidyr::pivot_wider(
      names_from = algo,
      values_from = value,
      id_cols = c(Study.ID, SUBJ, OSA, scale, side)
    ) |>
    dplyr::mutate(group = dplyr::case_when(
      SUBJ == "PD" & OSA ~ "PD, OSA+",
      SUBJ == "CON" & OSA ~ "HC, OSA+",
      SUBJ == "PD" & !OSA ~ "PD, OSA-",
      SUBJ == "CON" & !OSA ~ "HC, OSA-"
    ))
  # Plot it:
  lapply(rlang::set_names(unique(df$scale)), function(i) {
    pairplot_fun(subset(df, scale == i), i)
  })
}

#' Pair plots
#'
#' Helper function for plotting associations
#' of pairs of variable as scatter plots accompanied
#' by Pearson's correlation coefficients.
#'
#' @param data Tibble. Raw data.
#' @param group_title Character. Title of the plot.
#'
#' @retuns List of {GGally} pair plots.
#'
#' @export
pairplot_fun <- function(data, group_title = "") {
  data |>
    GGally::ggpairs(
      title = group_title,
      columns = c("aseg.stat", "segmentHA", "synthseg"),
      mapping = ggplot2::aes(colour = group),
      upper = list(
        continuous = GGally::wrap("cor", size = 4)
      ),
      lower = list(
        continuous = function(data, mapping, ...) {
          ggplot2::ggplot(data, mapping) +
            ggplot2::geom_point(alpha = 0.6) +
            ggplot2::geom_abline(
              slope = 1, intercept = 0, colour = "black"
            )
        }
      ),
      diag  = list(
        continuous = GGally::wrap("densityDiag", alpha = .5, colour = NA)
      )
    )
}


#' Correlate hippocampi with BMI
#'
#' Correlates volume estimates of hippocampi structures
#' with BMI.
#'
#' @param d0 Tibble. Raw data as generated by \code{preprocess_data}.
#' @param help List. Helpers as generated by \code{extract_helpers}.
#'
#' @returns ggplot with coloured tiles and number indicating
#'   correlations.
#'
#' @export
correlate_bmi <- function(d0, help) {
  df <- d0 |>
    select(Study.ID, BMI, tidyselect::all_of(help$hippo$name))
  corrs <- psych::corr.test(df[, -1])
  tibble::tibble(
    v = rownames(corrs$r),
    r = as.numeric(corrs$r[, "BMI"]),
    p = as.numeric(corrs$p[, "BMI"])
  ) |>
    dplyr::filter(v != "BMI") |>
    dplyr::mutate(
      structure = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$hippo, unique(structure[name == v[i]]))
        }), use.names = FALSE),
        levels = rev(unique(help$hippo$structure)),
        ordered = TRUE
      ),
      side = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$hippo, unique(side[name == v[i]]))
        }), use.names = FALSE),
        levels = c("Left", "Right"),
        ordered = TRUE
      ),
      block = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$hippo, unique(block[name == v[i]]))
        }), use.names = FALSE),
        levels = unique(help$hippo$block),
        ordered = TRUE
      ) |> dplyr::recode("Complexes" = "", "Parasubiculum" = " "),
      sig = dplyr::case_when(
        p < .05 & p >= .005  ~ "*",
        p < .005 & p >= .001  ~ "**",
        p < .001  ~ "***",
        .default = ""
      ),
      pRint = glue::glue("{rprint(r, 2)}{sig}")
    ) |>
    ggplot2::ggplot() +
    ggplot2::aes(x = side, y = structure, fill = r, label = pRint) +
    ggplot2::geom_tile(colour = "white") +
    ggplot2::geom_text(size = 3.5) +
    ggplot2::scale_fill_gradient2(
      low = "#4575B4",
      mid = "white",
      high = "#D73027",
      midpoint = 0,
      limits = c(-1, 1),
      name = "Pearon's r"
    ) +
    ggh4x::facet_grid2(block ~ side, scales = "free", space = "free") +
    ggplot2::labs(x = NULL, y = NULL) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      panel.grid = ggplot2::element_blank(),
      axis.ticks = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_text(size = 11),
      legend.position = "right"
    )
}
