#' Correlate hippocampi volumes
#'
#' Correlates volume estimates of hippocampi estimated
#' by different approaches
#'
#' @param d0 Tibble. Raw data as generated by \code{import_data}.
#' @param d1 Tibble. Preprocessed data as generated by
#'   \code{preprocess_data}.
#' @param help List. Helpers as generated by \code{extract_helpers}.
#'
#' @returns ggplot
#'
#' @export
correlate_volumes <- function(d0, d1, help) {
  # Extract variable of interest names:
  struct <- tibble::tibble(
    side = c(rep("Left", 4), rep("Right", 4)),
    source = rep(c("recon-all", "Freesurfer 8.0.0"), 4),
    measure = rep(c(rep("raw", 2), rep("scaled", 2)), 2),
    column = c(
      subset(help$subco, structure == "Hippocampus" & side == "Left")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Left")$var,
      subset(help$subco, structure == "Hippocampus" & side == "Left")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Left")$name,
      subset(help$subco, structure == "Hippocampus" & side == "Right")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Right")$var,
      subset(help$subco, structure == "Hippocampus" & side == "Right")$name,
      subset(help$hippo, structure == "Hippocampus" & side == "Right")$name
    )
  )
  # Prepare data:
  df <- d0 |>
    dplyr::select(
      Study.ID, SUBJ, AHI.F,
      tidyselect::all_of(subset(struct, measure == "raw")$column)
    ) |>
    dplyr::left_join(
      d1 |> dplyr::select(
        Study.ID, SUBJ, AHI.F,
        tidyselect::all_of(subset(struct, measure == "scaled")$column)
      ),
      by = dplyr::join_by(Study.ID, SUBJ, AHI.F),
      suffix = c("_raw", "_scaled")
    ) |>
    dplyr::mutate(
      PD = dplyr::if_else(SUBJ == "PD", TRUE, FALSE),
      OSA = dplyr::if_else(AHI.F == "H", TRUE, FALSE)
    ) |>
    dplyr::rename( # dirty by hand to save time
      "Raw_Left_recon-all" = "Left_Hippocampus_raw",
      "Raw_Left_Freesurfer 8.0.0" = "Whole_hippocampus_lhx",
      "Scaled_Left_recon-all" = "Left_Hippocampus_scaled",
      "Scaled_Left_Freesurfer 8.0.0" = "Hippocampus_left_AI",
      "Raw_Right_recon-all" = "Right_Hippocampus_raw",
      "Raw_Right_Freesurfer 8.0.0" = "Whole_hippocampus_rhx",
      "Scaled_Right_recon-all" = "Right_Hippocampus_scaled",
      "Scaled_Right_Freesurfer 8.0.0" = "Hippocampus_right_AI"
    )
  # Plot it:
  df |>
    tidyr::pivot_longer(
      cols = matches("^(Raw|Scaled)_(Left|Right)"),
      names_to = c("scale", "side", "algo"),
      names_pattern = "^(Raw|Scaled)_(Left|Right)_(.*)$",
      values_to = "value"
    ) |>
    # Clean algorithm names
    dplyr::mutate(
      scale = factor(scale, levels = c("Raw", "Scaled")),
      side  = factor(side,  levels = c("Left", "Right")),
      algo  = factor(algo,  levels = c("Freesurfer 8.0.0", "recon-all"))
    ) |>
    tidyr::pivot_wider(
      names_from = algo,
      values_from = value,
      id_cols = c(Study.ID, SUBJ, OSA, scale, side)
    ) |>
    ggplot2::ggplot() +
    ggplot2::aes(x = `Freesurfer 8.0.0`, y = `recon-all`) +
    ggplot2::geom_point(
      ggplot2::aes(color = OSA, fill = OSA),
      shape = 21,
      size = 2,
      alpha = 0.8
    ) +
    ggplot2::geom_smooth(
      ggplot2::aes(color = OSA, fill = OSA),
      method = "lm",
      linewidth = 0.5,
      alpha = 0.1
    ) +
    ggplot2::geom_abline(
      slope = 1, intercept = 0, colour = "red", linetype = 2
    ) +
    ggpubr::stat_cor(
      ggplot2::aes(label = ggplot2::after_stat(r.label)),
      label.x.npc = "left",
      label.y.npc = "top",
      size = 3.5
    ) +
    ggh4x::facet_grid2(SUBJ + side ~ scale, scales = "free", independent = "all") +
    ggplot2::scale_colour_manual(values = c("#64CDCC","#F9A729")) +
    ggplot2::scale_fill_manual(values = c("#64CDCC","#F9A729")) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      strip.background = ggplot2::element_rect(fill = "grey90"),
      panel.grid = ggplot2::element_blank(),
      legend.position = "bottom"
    )
}
