#' Document Paths to Data
#'
#' This function needs to be adjusted manually if
#' desired. It is used in the \pkg{targets} pipeline
#' to show data files locations when importing them.
#'
#' @param tracker A character vector. In the \pkg{targets}
#'    pipeline serves to control the flow if the raw data
#'    change.
#'
#' @returns A data.frame containing paths to data
#'
#' @export
data_paths <- function(tracker) {
  data.frame(
    lhippo = here::here("data-raw", "Tabhippsubfields_lh_new2.xlsx"),
    rhippo = here::here("data-raw", "Tabhippsubfields_rh_new2.xlsx"),
    subcor = here::here("data-raw", "asegTab.xlsx"),
    psych = here::here("data-raw", "RBDBIOPDCON_DATA_2024-07-17_1146.csv"),
    motor = here::here("data-raw", "BIOPD_MDSUPDRSIII.xlsx"),
    mta = here::here("data-raw", "MTA_table .xlsx")
  )
}

#' Document Paths to Helper Files
#'
#' This function needs to be adjusted manually if
#' desired. It is used in the \pkg{targets} pipeline
#' to show helper files locations when importing them.
#'
#' @param tracker A character vector. In the \pkg{targets}
#'    pipeline serves to control the flow if the helper
#'    files change.
#'
#' @returns A data.frame containing paths to helpers
#'
#' @export
helper_paths <- function(tracker) {
  data.frame(
    psychvar = here::here("data-raw", "psychs.csv"),
    calculat = here::here("data-raw", "calculator_final_v7_c_301116.xlsx"),
    calc_sheet = "equations",
    subcortex = here::here("data-raw", "subcortical.csv"),
    hippocampi = here::here("data-raw", "hippocampus.csv"),
    mta = here::here("data-raw", "mta.csv")
  )
}

#' Import Raw Data
#'
#' Takes in file paths to data and helper files,
#' imports the data and structure them properly.
#'
#' @param files A data.frame containing paths do data
#'    files generated by \code{data_paths}.
#' @param helpers A list containing helper files generated
#'    by \code{extract_helpers}
#'
#' @seealso [data_paths()], [extract_helpers()]
#'
#' @returns A tibble containing raw data.
#'
#' @export
import_data <- function(files, helpers) {
  # Read raw data:
  data <- with(files, {
    list(
      # MRI volummetry estimates
      subcor = openxlsx::read.xlsx(subcor) |>
        dplyr::rename_with(\(x) gsub("-", "_", x)) |>
        dplyr::rename_with(\(x) gsub(",", ".", x, fixed = TRUE)),
      hippo = dplyr::left_join(
        openxlsx::read.xlsx(rhippo) |>
          dplyr::rename_with(\(x) gsub("-", "_", x)) |>
          dplyr::mutate(dplyr::across(!tidyselect::ends_with("ID"), as.numeric)),
        openxlsx::read.xlsx(lhippo) |>
          dplyr::rename_with(\(x) gsub("-", "_", x)),
        by = "Study.ID",
        suffix = c("_rhx", "_lhx")
      ) |>
        dplyr::select(Study.ID, tidyselect::all_of(helpers$hippo$var)),
      mta = openxlsx::read.xlsx(mta) |>
        dplyr::select(Study.ID, tidyselect::contains("MTA")),
      # Psychology data
      psych = read.csv(psych, sep = ",") |>
        dplyr::mutate(
          Study.ID = sub("-", "", study_id),
          event = sub("_arm_2|_arm_3", "", redcap_event_name)
        ) |>
        dplyr::select(Study.ID, event, tidyselect::all_of(c(helpers$psychohelp$variable, "moca"))) |>
        dplyr::filter(event == "enrollment"),
      # MDS-UPDRS data
      motor = openxlsx::read.xlsx(motor, startRow = 2, check.names = TRUE) |>
        dplyr::mutate(
          age_first_symptom = lubridate::time_length(difftime(První.motorický.příznak.PN..MM.RRRR., Datum.narození), "years"),
          disease_duration = lubridate::time_length(difftime(Datum.vyšetření, První.motorický.příznak.PN..MM.RRRR.), "years"),
          event = "enrollment"
        ) |>
        dplyr::select(
          Study.ID, event, age_first_symptom, disease_duration,
          MDS.UPDRS.Část.I.sumární.skóre,
          MDS.UPDRS.Část.II.sumární.skóre..počítaná.hodnota.,
          MDS.UPDRS.Část.III..celkové.score., Axiasubscore, Rigidityakinesia, Tremorsubscoret
        ) |>
        dplyr::rename(
          "mds_updrs_i" = "MDS.UPDRS.Část.I.sumární.skóre",
          "mds_updrs_ii" = "MDS.UPDRS.Část.II.sumární.skóre..počítaná.hodnota.",
          "mds_updrs_iii_total" = "MDS.UPDRS.Část.III..celkové.score.",
          "mds_updrs_iii_axial" = "Axiasubscore",
          "mds_updrs_iii_rigidityakineasia" = "Rigidityakinesia",
          "mds_updrs_iii_tremor" = "Tremorsubscoret"
        )
      ) |>
      # Pull the data to a single file:
      purrr::reduce(dplyr::left_join)
  })
  # Add standardised volumes of subcortical structures:
  with(helpers, {
    for(i in seq_len(nrow(subco))) {
      data[ , subco$scaled[i]] <<- (data[ , subco$name[i]] / data$sBTIV) * mean(data$sBTIV)
    }
  })
  # Prepare objects for PD-MCI labelling:
  calculator <- helpers$calculator |>
    dplyr::filter(X1 %in% with(helpers$psychohelp, label[!is.na(pairs)])) |>
    dplyr::mutate(
      sign = dplyr::if_else(X1 %in% c("TMT-A","PST-C"), -1, 1),
      var = unlist(
        sapply(seq_len(dplyr::n()), function(i) {
          helpers$psychohelp[helpers$psychohelp$label == X1[i], "variable"]
        }),
        use.names = TRUE
      )
    )
  # Prepare thresholds for BNT-60:
  bnt_thresh <- data.frame(
    age_bottom = c(0, 0, 60, 60),
    age_top = c(60, 60, Inf, Inf),
    edu_bottom = c(0, 12, 0, 12),
    edu_top = c(12, Inf, 12, Inf),
    threshold = c(49, 52, 50, 53)
  )
  # Prepare a table for MoCA (i.e., lvl. I) (based on https://doi.org/10.1080/23279095.2015.1065261):
  moca_thresh <- data.frame(
    age_bottom = c(0, 0, 74, 74),
    age_top = c(74, 74, Inf, Inf),
    edu_bottom = c(0, 12, 0, 12),
    edu_top = c(12, Inf, 12, Inf),
    M = c(24.62, 26.43, 22.98, 24.79),
    SD = c(2.66, 2.37, 2.88, 2.47)
  ) |>
    dplyr::mutate(threshold = M - 1.5 * SD)
  # Add MCI flag for each test of each patient:
  mci <- data |>
    dplyr::filter(SUBJ == "PD") |> # keep patients only
    # Add MCI flags (i.e., z ≤ -1.5):
    dplyr::mutate(
      dplyr::across(
        .cols = calculator$var,
        .fns = \(x) zscore(calculator, x, dplyr::cur_column(), AGE, GENDER, EDU.Y),
        .names = "z_{.col}"
      ),
      dplyr::across(
        .cols = tidyselect::starts_with("z_"),
        .fns = \(x) dplyr::if_else(x <= -1.5, 1, 0),
        .names = "mci_{.col}"
      ),
      mci_bnt = sapply(seq_len(dplyr::n()), function(i) {
        ifelse(
          test = bnt60[i] <= with(bnt_thresh, threshold[AGE[i] > age_bottom & AGE[i] <= age_top & EDU.Y[i] > edu_bottom & EDU.Y[i] <= edu_top]),
          yes = 1,
          no = 0
        )
      }),
      PDMCI_I = sapply(seq_len(dplyr::n()), function(i) {
        ifelse(
          test = moca[i] <= with(moca_thresh, threshold[AGE[i] > age_bottom & AGE[i] <= age_top & EDU.Y[i] > edu_bottom & EDU.Y[i] <= edu_top]),
          yes = 1,
          no = 0
        )
      })
    ) |>
    # Evaluate PD-MCI:
    dplyr::select(Study.ID, tidyselect::starts_with("mci_"), PDMCI_I) |>
    dplyr::mutate(
      flags = rowSums(dplyr::across(tidyselect::starts_with("mci_")), na.rm = TRUE),
      nas = rowSums(is.na(dplyr::across(tidyselect::starts_with("mci_")))),
      PDMCI_II = dplyr::case_when(
        flags >= 2 ~ 1,
        flags == 0 & nas < 2 ~ 0,
        flags == 1 & nas == 0 ~ 0,
        .default = NA
      )
    ) |>
    dplyr::select(Study.ID, PDMCI_I, PDMCI_II)
  # Add PD-MCI to the data and return
  dplyr::left_join(data, mci)
}

#' Pre-process the Data
#'
#' Takes in raw data, helper files, response times
#' variables and indicator of the object that shall
#' be returned.
#'
#' @param data A data.frame containing raw data generated
#'    by \code{import_data}.
#' @param help A list containing helper files generated
#'    by \code{extract_helpers}
#' @param rt_vars A character of response times variables
#'    generated by \code{extract_rt_variables}
#' @param return A character indicating what shall be
#'    returned. Either "df" to return the data or "scl"
#'    to return scaling values.
#'
#' @returns A tibble containing raw data.
#'
#' @export
preprocess_data <- function(data, help, rt_vars, return = "df") {
  # Read the data:
  d0 <- data |>
    # Re-calculate hippocampal fields according to the legend in hippo:
    dplyr::mutate(
      !!!setNames(rep(NA, length(unique(help$hippo$name))), unique(help$hippo$name)),
      dplyr::across(
        .cols = unique(help$hippo$name),
        .fns = function(x) {
          rowSums(dplyr::across(tidyselect::all_of(with(help$hippo, var[name == dplyr::cur_column()]))))
        }
      )
    )
  # Format it for analyses:
  df <- d0 |>
    # Pre-process brain and demography variables:
    dplyr::mutate_if(is.character, as.factor) |>
    dplyr::mutate(
      PD = dplyr::if_else(SUBJ == "PD", 1, 0),
      GENDER = as.factor(GENDER),
      dplyr::across(tidyselect::all_of(rt_vars), \(x) -log(x)) # cognition
    ) |>
    # Set-up contrasts to avoid multicollinearity in interaction terms:
    within({
      contrasts(SUBJ) <- -contr.sum(2) / 2 # CON = -0.5, PD = 0.5
      contrasts(AHI.F) <- -contr.sum(2) / 2 # High = -0.5, Low = 0.5
      contrasts(GENDER) <- contr.sum(2) / 2 # female = 0.5, male = -0.5
    })
  # Extract scaling values, i.e.,
  # enrollment full sample means and SDs
  scl <- sapply(
    c("AGE", "EDU.Y", "BMI", "sBTIV", help$subco$name, unique(help$hippo$name), help$psych$variable),
    function(i) {
      with(df, c(M = mean(get(i), na.rm = TRUE), SD = sd(get(i), na.rm = TRUE)))
    }) |>
    t()
  # Scale the variables
  df <- df |>
    dplyr::mutate(
      dplyr::across(
        .cols = tidyselect::all_of(rownames(scl)),
        .fns = \(x) (x - scl[dplyr::cur_column(), "M"]) / scl[dplyr::cur_column(), "SD"]
      )
    )
  # Return the data:
  get(return)
}
