#' Describes the Sample
#'
#' Takes in data and computes descriptive statistics with
#' associated statistical tests for variables deemed
#' descriptive for the paper.
#'
#' @param data A data.frame generated by \code{import_data}.
#'
#' @returns A data.frame containing per group descriptive
#'    statistics.
#'
#' @export
describe_data <- function(data) {
  # List variables to be described:
  cont <- c(
    "AGE",
    "EDU.Y",
    "BMI",
    "age_first_symptom",
    "disease_duration",
    "moca",
    "mds_updrs_i",
    "mds_updrs_ii",
    "mds_updrs_iii_total",
    "mds_updrs_iii_axial",
    "mds_updrs_iii_rigidityakineasia",
    "mds_updrs_iii_tremor",
    "UPSIT",
    "uric_acid",
    "urea",
    "creatinine",
    "cholesterol",
    "TAG",
    "TSH",
    "fT4",
    "glucose",
    "Fazekas",
    "orto_tk_leh_sys",
    "orto_tk_leh_dia",
    "orto_tk_0_sys",
    "orto_tk_0_dia",
    "orto_tk_1_sys",
    "orto_tk_1_dia",
    "orto_tk_3_sys",
    "orto_tk_3_dia",
    "orto_pulz_leh",
    "orto_pulz_0",
    "orto_pulz_1",
    "orto_pulz_3"
  )
  nomin <- c(
    "GENDER",
    #"RBD",
    "Path_MTA_A",
    "Path_MTA_H",
    "PDMCI_I",
    "PDMCI_II",
    "orto_hypo",
    "an_rodina",
    "demence_rodina",
    "pn_rodina",
    "tres_rodina",
    "rbd_rodina",
    "uraz_opakovane",
    "uzkost_opak_kont",
    "deprese_opak_kont",
    "psychatricka_onemocneni",
    "hypercholesterolemie",
    "ichs",
    "arytmie",
    "hypertenze",
    "diabetes_mellitus",
    "thyreopatie",
    "icmp",
    "epilepsie",
    "polyneuropatie",
    "migreny",
    "encefalitis",
    "hcmp",
    "glaukom",
    "rls"
  )
  # Pre-process data:
  d0 <- data |>
    dplyr::mutate(dplyr::across(tidyselect::all_of(c(nomin, "SUBJ", "AHI.F")), as.factor)) |>
    within({
      contrasts(SUBJ) <- -contr.sum(2) / 2 # CON = -0.5, PD = 0.5
      contrasts(AHI.F) <- -contr.sum(2) / 2 # High = -0.5, Low = 0.5
    })
  # Prepare a table with descriptions
  tab1 <- d0 |>
    dplyr::group_by(GROUP) |>
    dplyr::summarise(
      dplyr::across(tidyselect::all_of(nomin), freqprop),
      dplyr::across(tidyselect::all_of(cont), msd)
    ) |>
    dplyr::ungroup() |>
    tibble::column_to_rownames("GROUP") |>
    t() |>
    as.data.frame() |>
    dplyr::mutate(dplyr::across(tidyselect::everything(), \(x) dplyr::if_else(grepl("NaN", x), "-", x))) |>
    tibble::rownames_to_column("y")
  # Add statistical analysis results of variables present in both PD and HC:
  tab1 <- dplyr::left_join(
    tab1, purrr::map_dfr(cont[c(1:3, 6, 13:length(cont))], function(y) {
      summary(lm(as.formula( paste0(y," ~ SUBJ * AHI.F")), data = d0))$coefficients[ , c("t value", "Pr(>|t|)")] |>
        statextract(y = y, stat = "t")
    }),
    by = "y"
  )
  # Add logistic regression for common variables:
  nomintest <- sapply(nomin, function(x) {
    if (stringr::str_detect(x, "MCI")) {
      FALSE
    } else {
      ncol(table(d0[ , c("GROUP", x)])) == 2
    }
  })
  nomintest <- nomin[nomintest]
  for (i in nomintest) {
    tab1[tab1$y == i, c("SUBJ1", "AHI.F1", "SUBJ1:AHI.F1")] <-
      summary(glm(as.formula(paste0(i, " ~ SUBJ * AHI.F")), family = binomial(), data = d0))$coefficients[ , c("z value","Pr(>|z|)")] |>
      statextract(y = i, stat = "z") |>
      dplyr::select(-y)
  }
  # Add logistic regression for iRBD and PD-MCI level I
  #for(i in c("RBD","PDMCI_I")) {
  for (i in c("PDMCI_I", "PDMCI_II")) {
    tab1[tab1$y == i, "AHI.F1"] <- summary(
      glm(
        as.formula(paste0(i," ~ AHI.F")),
        family = binomial(),
        data = subset(d0, SUBJ == "PD")
      )
    )$coefficients[ , c("z value","Pr(>|z|)")] |>
      statextract(y = i, stat = "z") |>
      dplyr::select(-y)
  }
  # Add results of continuous variables for PD only:
  for (i in with(tab1, y[CONH == "-"] )[-1:-2]) {
    tab1[ tab1$y == i, "AHI.F1"] <-
      summary(lm(as.formula(paste0(i," ~ AHI.F")), data = d0))$coefficients[ , c("t value", "Pr(>|t|)")] |>
      statextract(y = i, stat = "t") |>
      dplyr::select(-y)
  }
  # Return the table:
  tab1
}
