#' Plots Posterior Predictive Checks
#'
#' Loops through Bayesian regression models and returns
#' either prior sensitivity to power scaling table or
#' posterior predictive check figure.
#'
#' @param fit A nested list with Bayesian regression models
#' @param help Helper list generated by \code{extract_helpers}
#' @param formulas A nested list with formulas for
#'    Bayesian regression
#' @param which A character indicated whether prior
#'    sensitivity tables ("prior_sense", default) or
#'    posterior predictive check ("ppc") ought to be
#'    returned.
#'
#' @returns Either a nested list with prior sensitivity
#'    metrics or a list of plots with posterior predictive
#'    checks.
#'
#' @export
model_check <- function(fit, help, formulas, which = "prior_sense") {
  if ( which == "prior_sense") {
    # Check prior-sensitivity:
    lapply(rlang::set_names(names(fit)), function(i) {
      lapply(rlang::set_names(names(fit[[i]])), function(y) {
        priorsense::powerscale_sensitivity(fit[[i]][[y]])
      })
    })
  } else if (which == "ppc") {
    lapply(rlang::set_names(c("dens_overlay_grouped","stat_grouped")), function(k) {
      ppc <- lapply(rlang::set_names(names(fit)), function(i) {
        lapply(rlang::set_names(names(fit[[i]])), function(y) {
          # Set distinct colour palettes for different types of models:
          if (i == "varequal") {
            bayesplot::color_scheme_set(scheme = "red")
          } else if (i == "heteroscedastic") {
            bayesplot::color_scheme_set(scheme = "blue")
          }
          # Set seed for reproducibility:
          set.seed(87542)
          # Plotting proper:
          brms::pp_check(fit[[i]][[y]], ndraws = 100, type = k, group = "SUBJ", stat = "sd", bins = 12) +
            ggplot2::theme_bw(base_size = 14) +
            ggplot2::labs(
              x = paste0( with(help$psych, label[variable == y]), " (-log seconds)" ),
              title = dplyr::case_when(
                i == "varequal" ~ paste0(as.character(formulas[[i]][[y]])[1], "\nsigma ~ 1"),
                i == "heteroscedastic" ~ paste0(as.character(formulas[[i]][[y]])[1] , "\n", sub(")", "", sub("list(sigma = ", "", as.character(formulas[[i]][[y]])[2], fixed = TRUE))
                )
              ) |>
                re_formulate()
            ) +
            ggplot2::theme(
              legend.position = "none",
              panel.grid = ggplot2::element_blank(),
              plot.title = ggplot2::element_text(hjust = 0.5, size = 10)#,
              #plot.background = element_rect(fill = NA, colour  = 'black', linetype = "dashed", size = .5)
            )
        })
      })
      # Put them to a single plot:
      with(ppc, {
        (varequal$tmt_b | heteroscedastic$tmt_b) /
          (varequal$gpt_phk | heteroscedastic$gpt_phk) /
          (varequal$gpt_lhk | heteroscedastic$gpt_lhk)
      })
      # save it
      #ggsave(
      #  plot = last_plot(),
      #  filename = here( "figures", paste0("cognition_ppc_", sub("_.*","",k), ".jpg") ),
      #  dpi = 300,
      #  width = 12,
      #  height = 12
      #)
    })
  }
}
