#' Extract number of participants
#'
#' Counts participant in each subgroup.
#'
#' @param d0 Tibble. Data.
#' @param grps Character. Group columns in data.
#'
#' @returns List. Number of per-group participants
#'   in each grouping.
#'
#' @export
count_n <- function(d0, grps) {
  lapply(rlang::set_names(grps), function(i) {
    sapply(unique(d0[, i]), function(j) {
      length(unique(subset(d0, get(i) == j)$Study.ID))
    })
  })
}


#' Table descriptive statistics
#'
#' Prepares a {gt} table with descriptive
#' statistics.
#'
#' @param stats Tibble. Contains descriptive
#'   table as generated by \code{describe_data}.
#' @param vars Character vector. Contains names
#'   of variables to include in the order to
#'   included them in.
#' @param labs Character vector (optional). Contains
#'   labels for each variables. In the same order as
#'   `vars`.
#' @param note Character (optional). Contains information
#'   to be written in the source note.
#'
#' @returns A {gt} table.
#'
#' @export
table_descriptives <- function(stats, vars, labs = NULL, note = "") {
  if (is.null(labs)) {
    labs <- vars
  }
  tab <- stats |>
    dplyr::filter(y %in% vars) |>
    dplyr::mutate(y = factor(y, levels = vars, ordered = TRUE)) |>
    dplyr::arrange(y)
  tab |>
    dplyr::mutate(y = labs) |>
    dplyr::select(y, PDH, PDL, CONH, CONL, SUBJ1, AHI.F1, `SUBJ1:AHI.F1`) |>
    dplyr::mutate(
      dplyr::across(tidyselect::everything(), \(x) ifelse(is.na(x), "-", x))
    ) |>
    gt::gt(rowname_col = "y") |>
    gt::cols_align(columns = -1, align = "center") |>
    gt::tab_spanner(columns = tidyselect::starts_with("CON"), label = "CON") |>
    gt::tab_spanner(columns = tidyselect::starts_with("PD"), label = "PD") |>
    gt::tab_spanner(columns = tidyselect::ends_with("1"), label = "Inference statistics") |>
    gt::tab_spanner(columns = tidyselect::all_of(c("CONH", "CONL", "PDH", "PDL")), label = "Descriptive statistics") |>
    gt::cols_label(
      ends_with("L") ~ "OSA-",
      ends_with("H") ~ "OSA+",
      SUBJ1 ~ "Group",
      AHI.F1 ~ "OSA",
      `SUBJ1:AHI.F1` ~ "Group * OSA"
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_spanners("Descriptive statistics"),
      footnote = "Presented as mean ± standard deviation for continuous and count (percentage) for binary variables."
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_spanners("Inference statistics"),
      footnote = "Based on Gaussian (continuous variables) or logistic (binary variables) regressions with OSA (disease-specific variables) or Group, OSA and Group * OSA interaction predictor terms with coefficients computed via QR decomposition solution to the least squares problem as implemented in R glm() function."
    ) |>
    gt::tab_source_note(note)
}


#' Table regressions of subcortical volumes
#'
#' Prepares a {gt} table with regression statistics
#' derived from models regressing subcortical structures
#' volume estimates on PD, OSA, their interaction and
#' covariates.
#'
#' @param stats Tibble. Contains regression statistics
#'   as generated by \code{summarise_regressions}.
#' @param help List. Helper files extracted by
#'   \code{extract_helpers}.
#' @param note Character (optional). Contains information
#'   to be written in the source note.
#'
#' @returns A {gt} table.
#'
#' @export
table_subcortical <- function(stats, help, note = "") {
  stats |>
    dplyr::mutate(
      Side = unlist(sapply(seq_len(dplyr::n()), function(i) {
        with(help$subco, side[name == y[i]])
      }), use.names = FALSE),
      Structure = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$subco, structure[name == y[i]])
        }), use.names = FALSE),
        levels = unique(help$subco$structure),
        ordered = TRUE
      ),
      Coefficient = dplyr::case_when(
        coefficient == "Group1" ~ "Group",
        coefficient == "OSA1" ~ "OSA",
        coefficient == "Group1:OSA1" ~ "Group * OSA"
      ),
      Estimate = rprint(Estimate),
      SE = rprint(`Std. Error`),
      `95% CI` = glue::glue("[{rprint(`2.5 %`)}, {rprint(`97.5 %`)}]"),
      t = rprint(`t value`, 3),
      p = zerolead(`p value`),
      s = rprint(`s value`),
      sig = sig_FDR
    ) |>
    #dplyr::select(Side, Structure, Coefficient, Estimate, SE, `95% CI`, t, p, s, sig) |>
    dplyr::select(Side, Structure, Coefficient, Estimate, `95% CI`, t, p, s, sig) |>
    tidyr::pivot_wider(
      names_from = Side,
      #values_from = c("Estimate", "SE", "95% CI", "t", "p", "s", "sig")
      values_from = c("Estimate", "95% CI", "t", "p", "s", "sig")
    ) |>
    dplyr::arrange(Structure) |>
    gt::gt(groupname_col = "Structure") |>
    gt::tab_spanner(
      label = "Left hemisphere",
      columns = tidyselect::ends_with("Left"),
      gather = TRUE
    ) |>
    gt::tab_spanner(
      label = "Right hemisphere",
      columns = tidyselect::ends_with("Right"),
      gather = TRUE
    ) |>
    gt::cols_align(align = "center", columns = -c(1:2)) |>
    gt::cols_label(
      tidyselect::starts_with("Estimate_") ~ "{{:beta:}}",
      #tidyselect::starts_with("SE_") ~ "SE",
      tidyselect::starts_with("95%") ~ "95% CI",
      tidyselect::starts_with("t_") ~ "t value",
      tidyselect::starts_with("p_") ~ "p-value",
      tidyselect::starts_with("s_") ~ "s-value",
      tidyselect::starts_with("sig") ~ "sig."
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_labels(tidyselect::starts_with("Estimate_")),
      footnote = "Values based on in-sample standardised outcome predicted by Group, OSA, Group * OSA interaction, age, sex, and TIV via QR decomposition solution to the least squares problem as implemented in R lm() function. Negative values imply smaller adjusted volume of a subcortical structure in PD compared to HC (Group rows), OSA+ compared to OSA- (OSA row) or smaller OSA+ - OSA- difference in HC compared to PD (Group * OSA rows), the reverse is true for positive values."
    ) |>
    gt::tab_source_note(note)
}


#' Table regressions of hippocampal volumes
#'
#' Prepares a {gt} table with regression statistics
#' derived from models regressing hippocampal structures
#' volume estimates on PD, OSA, their interaction and
#' covariates.
#'
#' @param stats Tibble. Contains regression statistics
#'   as generated by \code{summarise_regressions}.
#' @param help List. Helper files extracted by
#'   \code{extract_helpers}.
#' @param note Character (optional). Contains information
#'   to be written in the source note.
#'
#' @returns A {gt} table.
#'
#' @export
table_hippocampi <- function(stats, help, note = "") {
  ord <- help$hippo |>
    dplyr::select(structure, order) |>
    dplyr::distinct() |>
    dplyr::arrange(order) |>
    dplyr::pull(structure)
  stats |>
    dplyr::mutate(
      Side = unlist(sapply(seq_len(dplyr::n()), function(i) {
        with(help$hippo, unique(side[name == y[i]]))
      }), use.names = FALSE),
      Structure = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$hippo, unique(structure[name == y[i]]))
        }), use.names = FALSE),
        levels = rev(ord),
        ordered = TRUE
      ),
      Block = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$hippo, unique(block[name == y[i]]))
        }), use.names = FALSE),
        levels = unique(hippo$block),
        ordered = TRUE
      ),
      Estimate = rprint(Estimate),
      SE = rprint(`Std. Error`),
      `95% CI` = glue::glue("[{rprint(`2.5 %`)}, {rprint(`97.5 %`)}]"),
      t = rprint(`t value`, 3),
      p = zerolead(`p value`),
      s = rprint(`s value`),
      sig = sig_FDR
    ) |>
    #dplyr::select(Block, Side, Structure, Estimate, SE, `95% CI`, t, p, s, sig) |>
    dplyr::select(Block, Side, Structure, Estimate, `95% CI`, t, p, s, sig) |>
    tidyr::pivot_wider(
      names_from = Side,
      values_from = c("Estimate", "95% CI", "t", "p", "s", "sig")
      #values_from = c("Estimate", "SE", "95% CI", "t", "p", "s", "sig")
    ) |>
    dplyr::arrange(Block) |>
    gt::gt(groupname_col = "Block") |>
    gt::tab_spanner(
      label = "Left hemisphere",
      columns = tidyselect::ends_with("Left"),
      gather = TRUE
    ) |>
    gt::tab_spanner(
      label = "Right hemisphere",
      columns = tidyselect::ends_with("Right"),
      gather = TRUE
    ) |>
    gt::cols_align(align = "center", columns = -c(1:2) ) |>
    gt::cols_align(align = "left", columns = 2) |>
    gt::cols_label(
      tidyselect::starts_with("Estimate_") ~ "{{:beta:}}",
      #tidyselect::starts_with("SE_") ~ "SE",
      tidyselect::starts_with("95%") ~ "95% CI",
      tidyselect::starts_with("t_") ~ "t value",
      tidyselect::starts_with("p_") ~ "p-value",
      tidyselect::starts_with("s_") ~ "s-value",
      tidyselect::starts_with("sig") ~ "sig."
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_labels(tidyselect::starts_with("Estimate_")),
      footnote = "Values based on in-sample standardised outcome predicted by Group, OSA, Group * OSA interaction, age, sex, and TIV via QR decomposition solution to the least squares problem as implemented in R lm() function. Negative values imply smaller OSA+ - OSA- difference in HC compared to PD, the reverse is true for positive values."
    ) |>
    tab_source_note(note)
}


#' Table regressions of cognitive indexes
#'
#' Prepares a {gt} table with regression statistics
#' derived from models regressing cognitive indexes
#' on PD, OSA, their interaction and covariates.
#'
#' @param stats Tibble. Contains regression statistics
#'   as generated by \code{summarise_regressions}.
#' @param help List. Helper files extracted by
#'   \code{extract_helpers}.
#' @param note Character (optional). Contains information
#'   to be written in the source note.
#'
#' @returns A {gt} table.
#'
#' @export
table_cognition <- function(stats, help, note) {
  stats |>
    dplyr::mutate(
      Index = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$psych, label[variable == y[[i]]])
        }), use.names = FALSE),
        levels = help$psych$label,
        ordered = TRUE
      ),
      Coefficient = dplyr::case_when(
        coefficient == "Group1" ~ "Group",
        coefficient == "OSA1" ~ "OSA",
        coefficient == "Group1:OSA1" ~ "Group * OSA"
      ),
      Estimate = rprint(Estimate),
      SE = rprint(`Std. Error`),
      `95% CI` = glue::glue("[{rprint(`2.5 %`)}, {rprint(`97.5 %`)}]"),
      t = rprint(`t value`, 3),
      p = zerolead(`p value`),
      s = rprint(`s value`),
      sig = sig_FDR
    ) |>
    #dplyr::select(Index, Coefficient, Estimate, SE, `95% CI`, t, p, s, sig) |>
    dplyr::select(Index, Coefficient, Estimate, `95% CI`, t, p, s, sig) |>
    dplyr::arrange(Index) |>
    gt::gt(groupname_col = "Index") |>
    gt::cols_align(align = "center", columns = -c(1:2)) |>
    gt::cols_label(
      tidyselect::starts_with("Estimate") ~ "{{:beta:}}",
      #tidyselect::starts_with("SE") ~ "SE",
      tidyselect::starts_with("95%") ~ "95% CI",
      tidyselect::starts_with("t") ~ "t value",
      tidyselect::starts_with("p") ~ "p-value",
      tidyselect::starts_with("s") ~ "s-value",
      tidyselect::starts_with("sig") ~ "sig."
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_labels("Estimate"),
      footnote = "Values based on in-sample standardised outcome predicted by Group, OSA, Group * OSA interaction, age, sex, and education via QR decomposition solution to the least squares problem as implemented in R lm() function. Negative values imply smaller adjusted volume of a subcortical structure in PD compared to HC (Group rows), OSA+ compared to OSA- (OSA row) or smaller OSA+ - OSA- difference in HC compared to PD (Group * OSA rows), the reverse is true for positive values."
    ) |>
    gt::tab_source_note(note)
}


#' Table coefficient comparisons
#'
#' Prepares a {gt} table with regression statistics
#' derived from models regressing cognitive indexes
#' on PD, OSA, their interaction and covariates.
#'
#' @param freq Tibble. Contains regression statistics
#'   as generated by \code{summarise_regressions}.
#' @param bayes Tibble. Contains Bayesian regression
#'   parameter estimates as generated by
#'   \code{extract_coefficients}.
#' @param help List. Helper files extracted by
#'   \code{extract_helpers}.
#' @param note Character (optional). Contains information
#'   to be written in the source note.
#'
#' @returns A {gt} table.
#'
#' @export
table_bayes <- function(freq, bayes, help, note = "") {
  bayes |>
    dplyr::mutate(
      type = paste0("Bayesian_", ifelse(sigma == 1, "classical", "distributional"))
    ) |>
    dplyr::full_join(
      freq |>
        dplyr::filter(y %in% unique(bayes$y)) |>
        dplyr::mutate(sigma = "1", type = "frequentist") |>
        dplyr::rename(
          "Est.Error" = "Std. Error",
          "Q2.5" = "2.5 %",
          "Q97.5" = "97.5 %"
        ) |>
        dplyr::select(type, tidyselect::all_of(colnames(bayes))),
      by = dplyr::join_by(y, X, sigma, coefficient, Estimate, Est.Error, Q2.5, Q97.5, type)
    ) |>
    dplyr::mutate(
      Index = factor(
        unlist(sapply(seq_len(dplyr::n()), function(i) {
          with(help$psych, label[variable == y[[i]]])
        }), use.names = FALSE),
        levels = help$psych$label,
        ordered = TRUE
      ),
      Coefficient = dplyr::case_when(
        coefficient == "Group1" ~ "Group",
        coefficient == "OSA1" ~ "OSA",
        coefficient == "Group1:OSA1" ~ "Group * OSA"
      ),
      Estimate = rprint(Estimate),
      SE = rprint(Est.Error),
      `95% CI` = glue::glue("[{rprint(Q2.5)}, {rprint(Q97.5)}]")
    ) |>
    dplyr::select(type, Index, Coefficient, Estimate, SE, `95% CI`) %>%
    tidyr::pivot_wider(
      names_from = type,
      values_from = c(Estimate, SE, `95% CI`)
    ) |>
    dplyr::arrange(Index) |>
    gt::gt(groupname_col = "Index") |>
    gt::tab_spanner(
      label = "Frequentist",
      columns = tidyselect::ends_with("frequentist"),
      gather = TRUE
    ) |>
    tab_spanner(
      label = "Distributional",
      columns = tidyselect::ends_with("distributional"),
      gather = TRUE
    ) |>
    tab_spanner(
      label = "Classical",
      columns = tidyselect::ends_with("classical"),
      gather = TRUE
    ) |>
    tab_spanner(
      label = "Bayesian",
      columns = tidyselect::contains("Bayesian"),
      gather = TRUE
    ) |>
    gt::cols_align(align = "center", columns = -c(1:2)) |>
    gt::cols_align(align = "left", columns = 2) |>
    gt::cols_label(
      tidyselect::starts_with("Estimate_") ~ "{{:beta:}}",
      tidyselect::starts_with("SE_") ~ "SE",
      "95% CI_frequentist" ~ "95% CI",
      tidyselect::starts_with("95% CI_Bayes") ~ "95% PPI"
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_labels(tidyselect::starts_with("Estimate_")),
      footnote = "Values based on in-sample standardised outcome predicted by Group, OSA, Group * OSA interaction, age, sex, and TIV via QR decomposition solution to the least squares problem as implemented in R lm() function. Negative values imply smaller OSA+ - OSA- difference in HC compared to PD, the reverse is true for positive values."
    ) |>
    gt::tab_source_note(note)
}
